N-BodyShop/changa

.travis.yml
teststep/Makefile
teststep/runtest.sh

A very simple script for initial testing of Travis CI.

Add Travis CI script

---

Sph.cpp

Change-Id: I4a001163e6cb2f4d82399d3a9662c5753f5f5fdf

arrayFileExists(): cleanup fscanf call.

---

cuda.mk.in

Add GPU_TREE_WALK flag to defines passed to all compilers.

---

Makefile.in

A couple of the configure tests change CPPFLAGS, but these were not making it into the Makefile.

Use configure determined CPPFLAGS in Makefile.

---

HierarchOrbLB.ci
ParallelGravity.cpp
TreePiece.cpp

Update to support Charm++'s LBDatabase->LBManager change

---

Makefile.in
configure
configure.ac

Move generation of cha_commitid.c to Makefile

---

ParallelGravity.cpp
TreePiece.cpp

A fix for https://github.com/N-BodyShop/changa_uw/issues/27

Fix possible overflow problem with large photogenic file reads.

---

dumpframe.cpp

This seems to only affect verbose output.
This fixes issue #67

Fix a couple of uninitialized memory issues in dumpframe.

---

dumpframe.cpp

Dumpframe: test and warn about return value of dfReadColorMapFile().

---

ParallelGravity.cpp

This is a fix for https://github.com/N-BodyShop/changa_uw/issues/263

Main::DumpFrameInit(): actually disable DumpFrame if iDirector == 0.

---

cooling_grackle.c
cooling_grackle.h

This is meant to fix issue #76

Fix comove scaling in grackle3

---

TreePiece.cpp

This fixes the changa_uw issue: https://github.com/N-BodyShop/changa_uw/issues/265

finishNodeCache(): be sure cache is synced before the finish.

---

Makefile.in

Force rebuild of cha_commitid.c

---

GravityParticle.h
ParallelGravity.ci
ParallelGravity.cpp
ParallelGravity.h
TreePiece.cpp
externalGravity.cpp

Revert "Py"

---

cooling_grackle.c
cooling_grackle.h

This fixes up the last commit to grackle3

grackle3 update COOLPARAM

---

ParallelGravity.cpp

Main::doSimulatoin(): no output for nSteps == 0 and bBenchmark.

---

InOutput.cpp
ParallelGravity.cpp

Only output igasorder when doing gas

---

HostCUDA.cu

Charm v7 has a slightly changed API for the work request infrastructure.

HostCuda.cu: add casts to accommodate changed setDeviceToHostCallback

---

.github/workflows/manga.yml

Add a github action to compile moving mesh.

Add github action for moving mesh.

---

ParallelGravity.cpp
ParallelGravity.h
SIDM.cpp
Sph.cpp
TreePiece.cpp
feedback.cpp
feedback.h
parameters.h
rand.h
sinks.cpp
starform.cpp
starform.h
supernova.cpp
supernova.h

Each Treepiece now has its own random number generator to avoid lock contention in threaded implementations.

Implement Press (version 3) Ran object.

---

InOutput.cpp

First assign extraData before using star methods.

Fixed bug introduced in commit 25c23a5074a3efbfa4aeb15b89430352415988c2

---

configure
configure.ac

This is to be paired with
[the corresponding utility pull request](https://github.com/N-BodyShop/utility/pull/7)
to use that xdr source if it can't be found on the system.

Look for xdr in utility.

---

ParallelGravity.cpp

ChaNGa will crash if there are not enough pieces to go around.

Check to be sure we have enough TreePieces for PEs.

---

supernovaia.cpp
testonestar/Makefile
testonestar/README
testonestar/energy.awk

Note that no simulation code is changed, just the code for testing.

Update test code in supernovaia.cpp and scripts in testonestar.

---

testcollapse/Makefile
testcollapse/compare.py

testcollapse/compare.py is updated to python3.

Update testcollapse script to python3
