InOutput.cpp

This is to avoid uninitialized data problems with the first tree build.  No science results are affected.

Initialize stellar Lyman-Werner for first tree build.

---

HostCUDA.cu

The 'size' variables were removed during code refactoring in 8234a97 and 8f4b45a.

Remove reference to non-existent variables in CUDA verbose output

---

HierarchOrbLB.cpp

This fixes a compile error with the latest version of charm.

Remove include of LBDBManager.h since it is gone from charm.

---

DataManager.cpp
InOutput.cpp
MultistepLB.cpp
Orb3dLB.cpp
Orb3dLBCommon.h
ParallelGravity.cpp
SIDM.cpp
Sorter.cpp
TreePiece.cpp
formatted_string.h
sinks.cpp

In the case where the precision depends upon a compile-time constant, the C-style printf was converted to using a formatted_string. This was done to simplify the code needed to get correct output for arbitrary types.

Clean up printf format warnings

---

InOutput.cpp
ParallelGravity.ci
ParallelGravity.cpp
ParallelGravity.h
TreePiece.cpp

Reset the charm timings after a restart, and do not do a domain
decomposition/load balance before entering doSimulation().
Also a code cleanup/documentation of the multi-phase load
infrastructure.

Perform better load balancing after a restart.

---

TreePiece.cpp

This fixes a hang discovered by Spencer: this loops through all possible owners of a requested TreeNode.

sendFillReqNodeWhenNull(): explore all possible Node owners.

---

InOutput.cpp

Also added some more code documentation.
Including output time in load balancing, particularly with non-Binary outputs can cause poor load balancing.  This appears to fix that issue.

TreePiece::reOrder(): turn off load balancing during outputs.

---

Sph.cpp
feedback.cpp

This fixes issues with uninitialized LW fluxes.

For H2 cooling, read in LW array files when restarting from an output.

---

InOutput.cpp
ParallelGravity.cpp

Also refactored the IC reading code.
The BlockMap layout has been broken for a while, causing a lot more messages in the initial domain decomposition.

BlockMap is obsolete for the initial TreePiece layout, so use DefaultArrayMap

---

HierarchOrbLB.cpp
HierarchOrbLB.h
Makefile.in

The Charm++ LB refactor has removed the CentralLB version of RefineLB,
this change removes ChaNGa's dependence on it by implementing RefineLB
directly in HierarchOrbLB. This is a stopgap change, eventually
HierarchOrbLB (and the other ChaNGa load balancers) will be rewritten
to use Charm++'s new TreeLB structure, which should make this code
considerably cleaner and more performant.

Remove dependence on RefineLB

---

Compute.cpp
DataManager.cpp
HostCUDA.cu
HostCUDA.h
cuda.mk.in

This PR unifies memory allocations for host pinned memory with `hapiMallocHost`, removing `CUDA_MALLOC`.
`hapiMallocHost`'s behavior will depend on the compile-time flags: with the default flags in `cuda.mk.in` (`-DHAPI_MEMPOOL` and `-DHAPI_USE_CUDAMALLOCHOST`) the allocations requests will go to the pinned host memory pool managed by HAPI.
This should be merged after https://github.com/UIUC-PPL/charm/pull/3017 in Charm++.

Unify host pinned memory allocation with hapiMallocHost

---

cooling_grackle.c
cooling_grackle.h

The grackle implementation of the CMB temperature floor has some weird effects at high densities, according to other codes in the AGORA collaboration.  Here a separate CMB floor implementation  is added to the cooling_grackle implementation with a parameter to turn it on.

Trq/grackle3: add a CMB temperature floor

---

configure
cuda.ac

Since Charm++ CUDA build can be used with both CUDA and non-CUDA builds of ChaNGa, the check that prevents non-CUDA ChaNGa from being built against Charm++ CUDA build should be disabled.

Remove check when building with Charm++ CUDA build

---

Sph.cpp
TreePiece.cpp

I ran into a problem with SUPERBUBBLE creating "hot" gas with infinite densities in TreePiece::updateuDot().
I believe the problem is that if a particle with a timestep as long as or longer than the star formation timestep gets supernova energy, the fSNErate gets reset at the next feedback event BEFORE uHot gets updated.  The solution here is to keep uHotDot() unchanged if cpHotInit is still set.

updateuDot(): handle superbubble feedback in slow particles.

---

DataManager.h

The new load balancing infrastructure in Charm++ obviates the need to
set the period to something small when using AtSync mode. Futher, it
disallows setting an LB period at all when using AtSync mode.

Remove deprecated calls to LBSetPeriod

---

HierarchOrbLB.cpp
HierarchOrbLB.h
MultistepLB.cpp
MultistepLB.h
MultistepLB_notopo.cpp
MultistepNodeLB_notopo.cpp
Orb3dLB.cpp
Orb3dLB.h
Orb3dLBCommon.h
Orb3dLB_notopo.cpp

I am trying to remove `CkVec` (which was originally used because `std::vector` wasn't available or portable enough) from the Charm++ LB infrastructure. This change makes ChaNGa agnostic to what the underlying data types are in the LB API.

LB: Remove dependency on CkVec from LB interface

---

MultistepLB.cpp
MultistepLB_notopo.cpp
MultistepNodeLB_notopo.cpp
Orb3dLB.cpp
Orb3dLBCommon.h
Orb3dLB_notopo.cpp

Accessing via a function allows the underlying implementation to
change, which Charm++ is doing to move away from raw memory
allocations.

LB: Use nprocs() instead of accessing count directly

---

ParallelGravity.cpp

The extra arrays for "nSteps = 0" outputs could end up in tree order rather than particle order.

Fix for getting output 0 arrays in correct order.

---

ParallelGravity.cpp

setupICs(): Report system error string on bad particle file open.

---

ParallelGravity.cpp

Disable LW output by default if we are not forming stars.

---

Compute.cpp

LocalLymanWernerDistributor::work(): cleanly handle nodes with no gas.

---

cooling_metal_H2.c

This makes the code more efficient and avoids a floating point overflow.

clRateColl_e_H2(): rewrite division into multiply.

---

InOutput.cpp
TreePiece.cpp
starform.cpp

This includes
1) setting iGasOrder = -1 for initial stars.  Otherwise it will be undefined.
2) Avoiding accessing cooling structures for adiabatic simulations.

Memory access cleanups

---

Makefile.in
other-codes/voro++-0.4.6/src/Makefile

This cleans up the use of CFLAGS and CXXFLAGS and allows CHARMC to have a relative path.

Fix make calls to other-codes directories.

---

ParallelGravity.cpp

This will help match performance data to particular simulation phases.

Add Elapsed time printouts to aid performance evaluation.

---

ParallelGravity.cpp
ParallelGravity.h
SIDM.cpp

This only is done if SIDM interactions are being counted.
This keeps track of the interaction count across restarts from outputs.

Read nsidm array if restarting from output.

---

Sph.cpp

This patch makes this code match what is in the changa_uw fork.

TreePiece::updateuDot(): use uPred and uHotPred in PoverRho calculation.

---

testcosmo/README
testcosmo/mf.sh
testcosmo/mf2.py

Added mf2.py, which is a python script that will test the simulation as a replacement for mf2.pro. Also modified mf.sh to make it run the new script, and to change some output file names from cube300.00128 that currently cause problems.

Added mf2.py in testcosmo

---

InOutput.cpp

An error message about which file caused the problem can save a lot of time!

More detailed error messages when opening tipsy array files.

---

InOutput.cpp

This avoids a (benign) access of uninitialized memory.
While this is benign, it is nice to have valgrind clean code.

Main::outputBinary(): always initialize iTypeWriting

---

TreePiece.cpp

Once sendParticlesDuringDD() has sent all the particles, myParticles can be deleted.  Doing it here lowers memory use.

SFC domain decomposition: delete particle store after messages are sent.

---

GravityParticle.h
TreePiece.cpp

and rearrange for better alignment.
This reduces GravityParticle from 144 to 104 bytes when --enable-float is set.

Change more GravityParticle attributes to cosmoType,

---

Sph.cpp

…because it creates instabilities.
This will match newer versions of Gasoline.
This addresses issue #146 as discussed with @robertwissing

PressureSmoothParams::fcnSmoth(): Remove fDivv_Corrector

---

DataManager.cpp
DataManager.h
Ewald.cpp
ParallelGravity.ci
ParallelGravity.h
TreePiece.cpp

This fixes a race condition where serializeLocal can sometimes be invoked before EwaldInit finishes. An EwaldMsg object is now passed to EwaldGPU, which tells whether EwaldInit, or the callback from the GPU memory transfer invoked it.
Note that the EwaldMsg only contains a single field here. EwaldMsg is used more extensively after the WorkRequest code has been removed from ChaNGa. These changes are contained in a separate pull request.

Fix GPU memory transfer + EwaldInit race condition

---

starform.cpp

Long standing format problem reported in the changa_uw fork.
N.B. This probably doesn't fix the problem reported on ~ 1/22/23 on slack.

Starlog::logMetaData(): fix small format error for H2FracForm

---

DataManager.h

Currently, PEs only utilize a single GPU per physical node, even if multiple devices are available. With this change, the user can split a physical node into virtual nodes and each virtual node will utilize a different GPU.
Note that using virtual nodes in SMP mode with projections enabled currently causes a CUDA memory error. This issue, however, is unrelated to the changes in this PR.

Assign GPUs to PEs based on node ID

---

.github/workflows/changa-smp.yml
.github/workflows/changa.yml

This changes the CI to use github clones to grab the charm distribution.

Github workflows: change source of charm distribution.

---

Compute.cpp
Compute.h
DataManager.cpp
DataManager.h
ParallelGravity.ci
ParallelGravity.cpp
ParallelGravity.h
TreePiece.cpp
feedback.cpp
parameters.h
starform.cpp

Although calculating gravity on the GPU is generally much faster, doing so introduces a significant amount of extra overhead. When using multistepping, it's often the case that using the GPU for gravity on higher rungs actually slows things down.
This PR introduces a new parameter 'nGpuMinParts', which triggers a tree walk on the CPU (instead of the GPU) whenever the number of active particles falls below the threshold.

Flexible GPU and CPU Usage for Gravity

---

feedback.cpp

Energy is put into either hot or cold phase, so account for both when checking on the energy
conservation.

massMetalsEnergyCheck(): correctly account SUPERBUBBLE energy

---

Makefile.in
MultistepLB_SFC.ci
MultistepLB_SFC.cpp
MultistepLB_SFC.h
MultistepLB_notopo.cpp
MultistepLB_notopo.h
MultistepNodeLB_notopo.cpp
Orb3dLBCommon.h
Orb3dLB_notopo.cpp
ParallelGravity.h
TreePiece.cpp

Not sure how well this works, but it might avoid some problems with the Orb load balancer.

Add SFC based Multistep load balancer.

---

Makefile.in

This breaks on ARM compiles, and it is not clear if it is ever needed on x86 architectures: all available x86 architectures are 64 bit by default.

Remove -m64 from target_arch

---

configure
configure.ac

This makes configure.ac consistent with configure.
I discovered the inconsistency when running "autoconf" after merging with another branch.

Disable collision by default in configure.ac

---

ParallelGravity.cpp
starform.h

The stochastic star formation code introduced an uninitialized memory problem that sometimes caused checkpoints to fail.
This also caused problems with some github CI runs.

Cleanup uninitialized memory problem in Stfm.

---

ParallelGravity.ci
feedback.h
parameters.h
starform.h

The Fdbk and Stfm classes have a lot of attributes for feedback and star formation, and they need to do a "deep copy" because of the IMF pointer.  It is too easy to forget to add a new parameter to the copy constructor resulting in uninitialized attributes in the class.  This was the root cause of a weird star formation history after a recent merge of star formation code with a downstream branch.
This is a rewrite so that the default constructor is used for the attributes, and only the IMF pointer gets the special constructor.
Note that the "pup" operators have a similar problem.  We should also think about rewriting those.

Simplified "deep copy" constructors needed for the IMF pointer.

---

InOutput.cpp
ParallelGravity.cpp
ParallelGravity.h

As well as reducing memory allocations/frees this fixes a "use after free" bug when writing outputs for "nSteps = 0".

Main::writeNCXML(): Use std::vector for NC*Names and avoid new/delete.
